### PR TITLE
Deliverable 3 - Jacks contributions

### PR DESCRIPTION
**Pull request by JLealos**
Starting pull request for deliverable 3

### CODE REVIEW

**Review by rudraamin06 — COMMENTED** [review]
Hey Jack I read your changes and I would suggest making sure the formatting is correct. I think you forgot to bold some of the noun for classes in our project.

**Review by rudraamin06 — COMMENTED** [review]
I think you should add a messageID as an input for the deleteMessage function.

**Review by NotYourAlejandro — CHANGES_REQUESTED** [review]
There will now be a Message class. Please remove all attributes and functions that would belong in that new class.

**Review by NotYourAlejandro — APPROVED** [review]
Diagram and paragraphs are good to go now.

**Pull request merged**
