### PR TITLE
Meeting Class Implementation

### PR DESCRIPTION
**Pull request by NotYourAlejandro**
This pull request contains the implementation for the Meeting class. It also has the required hooks into the Group class.

However, the tests have not been implemented yet. Check the comments below to see if this has changed.

Documentation on the usage will be created once this branch and #153 are merged into `dev` as they rely on each other.

### CODE REVIEW

**Comment by NotYourAlejandro** [comment]
I've been working on the tests, but those will be added in a separate pull request because it depends on the changes/refactors from #153.

**Comment by NotYourAlejandro** [comment]
Also, I haven't been wanting to test these functions out manually because the changes from #153 haven't been added to this or the `dev` branch yet, which makes requests quite difficult and tedious.

Manual and automated testing will begin once this and the other mentioned branch are merged into `dev`.

**Comment by NotYourAlejandro** [comment]
Oops, forgot about the .ics requirements. I'll add those, then comment when this pull req can be reviewed.

**Comment by NotYourAlejandro** [comment]
The remaining .ics requirements have been added, though idk if it's compliant with the full .ics spec (nor will I check, since that requires a ton of time and effort).

This pull request is good to be reviewed again!

**Review by jadynlaila — COMMENTED** [review]
Implementation looks great! Thank you Alex as always :)

**Pull request merged**
