### PR TITLE
Jadyns deliverable2

### PR DESCRIPTION
**Pull request by jadynlaila**

### CODE REVIEW

**Comment by rudraamin06** [comment]
Hey Jadyn, your picture for the use case isn't showing up correctly.

**Comment by rudraamin06** [comment]
Hey Jadyn, the image still isn't showing correctly.

**Review by daira27 — CHANGES_REQUESTED** [review]
Hey Jadyn it looks like in user stories, your stories show as headings instead of text.

**Review by daira27 — APPROVED** [review]
Thank you! Looks fire!

**Pull request merged**
