### PR TITLE
Deliverable 3 - Alex's Contributions

### PR DESCRIPTION
**Pull request by NotYourAlejandro**

### CODE REVIEW

**Comment by JLealos** [comment]
User settings UML class is good

**Comment by NotYourAlejandro** [comment]
The diagram is **NOT READY**, but the nonfunctional requirement paragraphs should be good.

**Review by NotYourAlejandro — COMMENTED** [review]
This branch is now completely ready for review.

**Review by vsv7nau — CHANGES_REQUESTED** [review]
change "architected" to structured. Just basic grammar and word stuff

**Review by vsv7nau — APPROVED** [review]
Great job, everything looks good.

**Pull request merged**
