### PR TITLE
Jack_d2

### PR DESCRIPTION
**Pull request by JLealos**
Added user stories and use case diagram for searching for a group.

### CODE REVIEW

**Comment by jadynlaila** [comment]
Hey Jack, please make sure the success and alternative scenario section of 6.2 are formatted correctly!

**Comment by rudraamin06** [comment]
Hey Jack, you also need to add Interface Sketch for your use case interface sketch.

**Review by daira27 — CHANGES_REQUESTED** [review]
Fix the format of user stories, make sure to add bullet points and indentations.

**Review by daira27 — APPROVED** [review]
Looks good! Thank you for fixing!

**Pull request merged**
